apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: 1
  template:
    metadata:
      labels:
        app: flask-app
        version: 1
    spec:
      containers:
      - name: flask-app
        image: namlai000/capstone:1.0
        ports:
        - containerPort: 80