version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  create-deployment:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source vent/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source vent/bin/activate
            make lint
      # - aws-eks/update-kubeconfig-with-authenticator:
      #     cluster-name: eks-capstone
      #     install-kubectl: true
workflows:
  deployment:
    jobs:
      - create-deployment